import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, MapPin } from "lucide-react";
import { WhatsAppIcon } from "@/components/whatsapp-icon";
import { PublicShell } from "@/components/public-shell";
import { metadata as makeMetadata } from "@/lib/seo";
import { whatsappUrl } from "@/lib/whatsapp";

const cities: Record<string,{title:string; intro:string; points:string[]; needs:string[]}> = {
  makkah:{ title:"Makkah accommodation that fits your journey",intro:"Whether walking distance, a shuttle, room space or budget is your priority, tell us what you need. Our team will check suitable hotel options for your dates.",points:["Distance from Masjid al-Haram can make a real difference for families and older travelers.","Check room setup, meal plan and transport needs before choosing.","Share your budget so we can focus the search."],needs:["Near Haram","Budget Friendly","Family Friendly","Elderly Friendly"] },
  madinah:{ title:"Find the right stay in Madinah",intro:"Plan a comfortable stay around your visit to Masjid an-Nabawi. Tell us your dates, group size, location preference and budget.",points:["Consider walking distance and access for everyone in your group.","Tell us if you need breakfast or a particular room setup.","We will check available options before sending a quote."],needs:["Near Masjid an-Nabawi","Family Friendly","Breakfast","Elderly Friendly"] },
  jeddah:{ title:"Jeddah stays, made easier to choose",intro:"A stopover, family visit or longer trip deserves a hotel that works for your plans. We can help compare suitable accommodation in Jeddah.",points:["Tell us the area that works best for your visit.","Share your room and budget preferences.","Our team will check options for your dates."],needs:["Family Friendly","Budget Friendly","Breakfast"] },
  riyadh:{ title:"Accommodation help for Riyadh",intro:"Tell us where you need to be, when you are traveling and what kind of stay feels right. We will look for suitable Riyadh options.",points:["A useful location can save time in a large city.","Let us know if you are traveling for work or with family.","Compare clear final prices before deciding."],needs:["Family Friendly","Budget Friendly","4 Star"] }
};
const cityImages: Record<string,{src:string;alt:string}> = {
  makkah:{src:"/images/makkah.jpg",alt:"Abraj Al Bait and the Grand Mosque in Makkah"},
  madinah:{src:"/images/madinah.jpg",alt:"The Prophet's Mosque in Madinah at dusk"},
  jeddah:{src:"/images/jeddah.jpg",alt:"The Jeddah waterfront and a white seaside mosque"},
  riyadh:{src:"/images/riyadh.jpg",alt:"Aerial view of Riyadh's central skyline"},
};
const pages: Record<string,{title:string;intro:string;sections:{heading:string;body:string}[]}> = {
  about:{title:"Thoughtful help for Saudi stays",intro:"MaqamStay helps travelers, especially families, choose accommodation in Saudi Arabia with more clarity and less guesswork.",sections:[{heading:"Built around your needs",body:"Travel plans vary. Some guests need a short walk, others prioritize a budget, room space or accessible travel with parents. We start by listening."},{heading:"An assisted service",body:"Our team checks options with accommodation suppliers and shares a customer quote. Availability, pricing and booking confirmation are handled manually."}]},
  faq:{title:"Frequently asked questions",intro:"Clear answers before you send your plans.",sections:[{heading:"Is hotel availability shown live?",body:"No. We check accommodation options after receiving your request, then share what is suitable and available at that time."},{heading:"Do I need to create an account?",body:"No. Send your request and continue the conversation on WhatsApp."},{heading:"Can I request hotels in both Makkah and Madinah?",body:"Yes. Select both destinations and enter separate dates for each."},{heading:"How do I book?",body:"Choose an option from the quote and contact us through WhatsApp. Our team will explain the manual booking and confirmation steps."},{heading:"Do you take payment online?",body:"No. MaqamStay does not process online payments in this version. Payment arrangements are discussed during booking."}]},
  contact:{title:"Let’s talk about your stay",intro:"Tell us your plans through the request form or message the MaqamStay team on WhatsApp.",sections:[{heading:"Accommodation requests",body:"The request form helps us collect your destination, dates and preferences so we can respond with relevant options."},{heading:"WhatsApp",body:"Use the WhatsApp button to start a conversation. Please include your request number if you already submitted a form."}]},
  privacy:{title:"Privacy Policy",intro:"We use your information to respond to your accommodation request and help arrange a stay.",sections:[{heading:"Information we collect",body:"We collect your name, contact details, destination, dates, group size, budget, preferences and any additional information you choose to provide."},{heading:"How we use it",body:"We use this information to understand your needs, contact accommodation suppliers, prepare quotes, communicate with you and record bookings. We share only information necessary to obtain options and arrange a booking."},{heading:"Storage and access",body:"Authorized MaqamStay staff access request and booking records. Quote links are private bearer links, so please share them only with people you trust."},{heading:"Your choices",body:"You can request correction or deletion of your information through our contact channel, subject to records we must retain for business or legal reasons. Analytics tools may be enabled later and will be configured through this site's environment."}]},
  terms:{title:"Terms of Service",intro:"Please read these terms before requesting accommodation assistance.",sections:[{heading:"Our service",body:"MaqamStay provides assisted accommodation search and booking coordination. The website is not a live hotel inventory or instant booking service."},{heading:"Quotes and availability",body:"Hotel options, prices, room details and cancellation terms are subject to supplier confirmation. A quote is not a confirmed booking."},{heading:"Booking and payment",body:"A booking is confirmed only when we provide confirmation details. Payment may be made directly to a supplier under the terms communicated during booking. MaqamStay does not collect online payments through this site."},{heading:"Changes and cancellation",body:"Hotel and supplier cancellation conditions vary. Review the terms attached to each quoted option and ask us if anything is unclear."}]}
};
export function generateStaticParams(){return [...Object.keys(cities),...Object.keys(pages)].map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=cities[slug]||pages[slug];return item?makeMetadata(item.title,item.intro,`/${slug}`):{};}
export default async function SlugPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const city=cities[slug],page=pages[slug];if(!city&&!page)notFound();const title=city?.title||page.title,intro=city?.intro||page.intro;return <PublicShell><section className={city?"page-hero city-hero":"page-hero"}><div className={city?"container city-hero-grid":"container"}><div className="city-hero-copy"><p className="kicker">{city?"DESTINATION GUIDE":"MAQAMSTAY"}</p><h1>{title}</h1><p>{intro}</p><Link href={`/request${city?`?destination=${slug.toUpperCase()}`:""}`} className="button button-primary">Get hotel options <ArrowRight size={17}/></Link></div>{city&&<div className="city-hero-photo"><Image src={cityImages[slug].src} alt={cityImages[slug].alt} fill sizes="(max-width: 650px) 100vw, (max-width: 950px) 44vw, 500px" preload/></div>}</div></section>{city?<section className="content-section"><div className="container"><div className="section-head"><div><p className="kicker">PLAN WITH CONFIDENCE</p><h2>What to consider in {slug[0].toUpperCase()+slug.slice(1)}</h2></div></div><div className="info-grid">{city.points.map((p,i)=><div className="info-card" key={p} data-reveal><MapPin color="#b48a4a" size={25}/><h3>{["Location","Comfort","Budget"][i]}</h3><p>{p}</p></div>)}</div><div style={{marginTop:38}}><p className="kicker">COMMON PREFERENCES</p><div className="needs-grid">{city.needs.map(n=><Link className="need-card" href={`/request?destination=${slug.toUpperCase()}&need=${encodeURIComponent(n)}`} key={n}>{n}<ArrowRight size={16}/></Link>)}</div></div></div></section>:<section className="content-section"><div className="container content-narrow">{page.sections.map(s=><div key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p></div>)}{slug==="contact"&&<a className="button button-secondary" href={whatsappUrl("Assalamualaikum, I'd like to ask about accommodation in Saudi Arabia.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={20}/> Chat on WhatsApp</a>}</div></section>}</PublicShell>}
