import Decimal from "decimal.js";
import { db } from "@/lib/db";
import { dateLabel, titleCase } from "@/lib/format";
import { money } from "@/lib/pricing";

type BookingRow=Awaited<ReturnType<typeof loadBookings>>[number];
type Total={name:string;currency:string;expected:Decimal;realized:Decimal};
const loadBookings=()=>db.booking.findMany({include:{commissions:true,supplier:true,option:true},orderBy:{createdAt:"desc"}});
const periodName=(date:Date,now:Date)=>{const month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const last=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-1,1));return date>=month?"This month":date>=last?"Last month":"Earlier"};
function totals(rows:BookingRow[],key:(row:BookingRow)=>string){const map=new Map<string,Total>();for(const row of rows){const name=key(row),id=`${name}|${row.currency}`;const total=map.get(id)||{name,currency:row.currency,expected:new Decimal(0),realized:new Decimal(0)};if(row.commissions.some(c=>c.status!=="VOID"))total.expected=total.expected.plus(row.expectedCommission.toString());if(row.commissions.some(c=>c.status==="RECEIVED"))total.realized=total.realized.plus(row.actualCommission?.toString()||row.expectedCommission.toString());map.set(id,total)}return [...map.values()]}
function periodTotals(rows:BookingRow[]){const now=new Date(),map=new Map<string,Total>();const add=(name:string,currency:string,type:"expected"|"realized",value:string)=>{const id=`${name}|${currency}`;const total=map.get(id)||{name,currency,expected:new Decimal(0),realized:new Decimal(0)};total[type]=total[type].plus(value);map.set(id,total)};for(const row of rows){if(row.commissions.some(c=>c.status!=="VOID"))add(periodName(row.createdAt,now),row.currency,"expected",row.expectedCommission.toString());for(const commission of row.commissions){if(commission.status==="RECEIVED"&&commission.receivedAt)add(periodName(commission.receivedAt,now),row.currency,"realized",commission.amount.toString())}}return [...map.values()].sort((a,b)=>["This month","Last month","Earlier"].indexOf(a.name)-["This month","Last month","Earlier"].indexOf(b.name))}
function Summary({title,rows}:{title:string;rows:Total[]}){return <section className="admin-panel detail-panel"><h2>{title}</h2>{rows.length===0?<p className="empty-state">No records.</p>:<div className="table-scroll"><table className="admin-table"><thead><tr><th>Group</th><th>Expected</th><th>Realized</th><th>Outstanding</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.name}${r.currency}`}><td>{r.name}</td><td>{money(r.expected.toString(),r.currency)}</td><td>{money(r.realized.toString(),r.currency)}</td><td>{money(Decimal.max(0,r.expected.minus(r.realized)).toString(),r.currency)}</td></tr>)}</tbody></table></div>}</section>}
export default async function Commissions(){const rows=await loadBookings();return <div className="admin-content"><div className="admin-page-head"><div><p className="kicker">FINANCIAL TRACKING</p><h1>Commissions</h1><p>Gross commission before expenses, separated by currency.</p></div></div><div className="admin-card-grid"><Summary title="By period" rows={periodTotals(rows)}/><Summary title="By supplier" rows={totals(rows,r=>r.supplier.name)}/><Summary title="By destination" rows={totals(rows,r=>titleCase(r.option.destination))}/></div><div className="admin-panel detail-panel"><h2>Recent commission records</h2><div className="table-scroll"><table className="admin-table"><thead><tr><th>Booking</th><th>Date</th><th>Supplier</th><th>Destination</th><th>Expected</th><th>Realized</th><th>Status</th></tr></thead><tbody>{rows.slice(0,30).map(r=><tr key={r.id}><td>{r.reference}</td><td>{dateLabel(r.createdAt)}</td><td>{r.supplier.name}</td><td>{titleCase(r.option.destination)}</td><td>{r.commissions.some(c=>c.status==="VOID")?"—":money(r.expectedCommission.toString(),r.currency)}</td><td>{r.commissions.some(c=>c.status==="RECEIVED")?money(r.actualCommission?.toString()||r.expectedCommission.toString(),r.currency):"—"}</td><td>{r.commissions.some(c=>c.status==="RECEIVED")?"Received":r.commissions.some(c=>c.status==="VOID")?"Void":"Outstanding"}</td></tr>)}</tbody></table></div></div></div>}
