import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getAdmin } from "@/lib/auth";
import { adminWriteGuard, failure } from "@/lib/http";
import { statuses } from "@/lib/validation";
import { canTransition } from "@/lib/workflow";
const schema=z.object({status:z.enum(statuses).optional(),supplierId:z.uuid().nullable().optional(),assignedToId:z.uuid().nullable().optional()}).refine(v=>Object.keys(v).length>0);
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const guard=await adminWriteGuard();if(guard)return guard;const admin=(await getAdmin())!;try{const {id}=await params;const data=schema.parse(await req.json());const current=await db.accommodationRequest.findUnique({where:{id}});if(!current)return NextResponse.json({error:"Request not found"},{status:404});if(data.status&&!canTransition(current.status,data.status))return NextResponse.json({error:`Cannot change ${current.status} to ${data.status}`},{status:409});if(data.status==="OPTIONS_RECEIVED"&&!await db.hotelOption.count({where:{requestId:id}}))return NextResponse.json({error:"Add a hotel option first"},{status:409});if(data.status==="QUOTE_SENT"&&!await db.quote.count({where:{requestId:id}}))return NextResponse.json({error:"Create a quote first"},{status:409});if(data.status==="BOOKED"&&!await db.booking.count({where:{requestId:id,status:"CONFIRMED"}}))return NextResponse.json({error:"Confirm a booking first"},{status:409});if(data.supplierId&&!await db.supplier.findFirst({where:{id:data.supplierId,active:true}}))return NextResponse.json({error:"Supplier not found or inactive"},{status:400});if(data.assignedToId&&!await db.adminUser.findFirst({where:{id:data.assignedToId,active:true}}))return NextResponse.json({error:"Staff member not found"},{status:400});const updated=await db.$transaction(async tx=>{const row=await tx.accommodationRequest.update({where:{id},data});await tx.activityLog.create({data:{requestId:id,actorId:admin.id,type:data.status==="CANCELLED"?"REQUEST_CANCELLED":data.status==="SUPPLIER_REQUESTED"?"SUPPLIER_CONTACTED":data.status==="QUOTE_SENT"?"QUOTE_SENT":"REQUEST_UPDATED",description:data.status?`Status changed to ${data.status.replaceAll("_"," ")}`:data.supplierId?"Supplier assigned":"Staff assignment updated"}});return row});return NextResponse.json({id:updated.id,status:updated.status});}catch(error){return failure(error)}}
