"use client";
import { useEffect } from "react";
import Script from "next/script";
import { usePathname } from "next/navigation";
import { track } from "@/lib/analytics";
const ga=process.env.NEXT_PUBLIC_GA_ID?.match(/^G-[A-Z0-9]+$/)?.[0];
const ads=process.env.NEXT_PUBLIC_GOOGLE_ADS_ID?.match(/^AW-[0-9]+$/)?.[0];
const pixel=process.env.NEXT_PUBLIC_META_PIXEL_ID?.match(/^[0-9]+$/)?.[0];
export function AnalyticsProvider(){const path=usePathname();const privatePage=path.startsWith("/quote/")||path.startsWith("/admin")||path.startsWith("/request/success");useEffect(()=>{if(!privatePage&&ga)window.gtag?.("event","page_view",{page_location:`${window.location.origin}${path}`})},[path,privatePage]);useEffect(()=>{const handler=(event:MouseEvent)=>{const link=(event.target as Element|null)?.closest?.("a[href*='wa.me/']");if(link)track("whatsapp_clicked",{source:window.location.pathname})};document.addEventListener("click",handler);return()=>document.removeEventListener("click",handler)},[]);if(privatePage)return null;return <>{(ga||ads)&&<><Script src={`https://www.googletagmanager.com/gtag/js?id=${ga||ads}`} strategy="afterInteractive"/><Script id="maqamstay-google-analytics" strategy="afterInteractive" dangerouslySetInnerHTML={{__html:`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}window.gtag=gtag;gtag('js',new Date());${ga?`gtag('config','${ga}',{send_page_view:false});`:""}${ads?`gtag('config','${ads}',{send_page_view:false});`:""}`}}/></>}{pixel&&<Script id="maqamstay-meta-pixel" strategy="afterInteractive" dangerouslySetInnerHTML={{__html:`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${pixel}');fbq('track','PageView');`}}/>}</>}
